### ISSUE TITLE
BetaToken has been removed

### ISSUE THREAD

**Issue by moemoe89** [sergeylanzman/newrelic_beego#1]
Hi, nice library, i want to inform you that go agent has been removed the beta token https://github.com/newrelic/go-agent/commit/903f9fc9987fb58fcb5a1f18f8fd2f378893bfa0

And i've been setup the app name + app license key, but on my new relic, the app not shown in APM.  Any idea about this ?

Thank you

**Comment by sergeylanzman** [comment]
Thank you for you report
I remove beta token now and check again if this work with newrelic agent 1.0.  Work now.
I dont know why you not see your app in APM, check now after update

**Comment by moemoe89** [comment]
You're welcome

I'm just trying. And still not shown on APM
How to use this ?
just import _ "github.com/sergeylanzman/newrelic_beego"
and set the appname & newrelic_license on beego conf right ?

Thank you

**Comment by sergeylanzman** [comment]
yap... only import and set newrelic_license
wait 5 minutes after start app before check in APM.
if not work try set in main func newrelic agent for test https://github.com/newrelic/go-agent

**Comment by moemoe89** [comment]
Hi Sergey,

Thank you for your support. Unfortunately the app still not shown on APM. I've wait 5 minutes, and try to adding 

config := newrelic.NewConfig("Your Application Name", "**YOUR_NEW_RELIC_LICENSE_KEY**")
app, err := newrelic.NewApplication(config)

but seems not work :(
Still don't have any idea what wrong with my configuration ?  Because i'm trying to use this https://github.com/yvasiyarov/beego_gorelic and successfully added to new relic. But just on plugins. We need to monitoring through APM like yours. Thank you

**Comment by moemoe89** [comment]
Sorry, my fault. the app has been shown on APM. Thank you.
