### ISSUE TITLE
The url path is wrong

### ISSUE THREAD

**Issue by xuxiaohu** [sergeylanzman/newrelic_beego#4]
My Request is /api/v1706/albums/11140.
The Result is /api/v:id/albums/:id
At Line 22, Original is
re := regexp.MustCompile("[0-9]{2,}")
I suggest
re := regexp.MustCompile("/[0-9]{2,}")

**Comment by sergeylanzman** [comment]
fix in https://github.com/sergeylanzman/newrelic_beego/pull/5
